/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACol: typeof import('@arco-design/web-vue')['Col']
    AList: typeof import('@arco-design/web-vue')['List']
    AListItem: typeof import('@arco-design/web-vue')['ListItem']
    ARow: typeof import('@arco-design/web-vue')['Row']
    Leaderboard: typeof import('./src/components/Leaderboard.vue')['default']
    MacOSWindow: typeof import('./src/components/MacOSWindow.vue')['default']
  }
}
